name: Nightly Sync
on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: | 
          curl --create-dirs -L -o "$HOME/.local/bin/pkl" https://github.com/apple/pkl/releases/download/0.25.2/pkl-linux-amd64
          chmod +x "$HOME/.local/bin/pkl"
          pkl --version
      - run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git submodule update --init --recursive
          git submodule update --recursive --remote
      - name: Build pkl-vscode
        working-directory: pkl-vscode
        run: npm install && npm run build
      - name: Generate dist 
        working-directory: .
        run: npm install && node index.js
      - run: ./scripts/nightly-commit.sh
